spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:"


greeting-service:
  greeting: "Hole"
  default-value: "Mundo"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
