server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#resilience4j:
#  retry:
#    instances:
#      foo-bar:
#        max-attempts: 5
#        wait-duration: 5
#        enable-exponential-backoff: true
#  ratelimiter:
#    instances:
#      default:
#        limit-for-period: 2
#        limit-refresh-period: 10s
#  bulkhead:
#    instances:
#      default:
#        max-concurrent-calls: 10
#      default:
#        max-attempts: 3
spring:
  application:
    name: autentication-service
  datasource:
    url: jdbc:postgresql://localhost:5433/autentication-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    url: jdbc:postgresql://localhost:5433/autentication-service
    user: postgres
    password: postgres
    baseline-on-migrate: true
    validate-on-migrate: false
    table: service1_flyway_schema_history
    baseline-version: 0
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0
#  config:
#    import: "optional:configserver:"
springdoc:
  api-docs:
    path: autentication-service/v3/api-docs
  show-actuator: true
