server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:postgresql://localhost:5433/cambio_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    url: jdbc:postgresql://localhost:5433/cambio_service
    user: postgres
    password: postgres
    baseline-on-migrate: true
    validate-on-migrate: false
    table: service1_flyway_schema_history
    baseline-version: 0
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
#  config:
#    import: "optional:configserver:"
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  show-actuator: true
