server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
#  config:
#    import: "optional:configserver:"
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
      - id: pedido-service
        uri: lb://pedido-service
        predicates:
        - Path=/pedido-service/**
      - id: buscacep-service
        uri: lb://buscacep-service
        predicates:
        - Path=/buscacep-service/**
      - id: cadastro-service
        uri: lb://cadastro-service
        predicates:
        - Path=/cadastro-service/**
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: autentication-service
        uri: lb://autentication-service
        predicates:
        - Path=/autentication-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs