server:
  port: 8404
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: buscacep-service
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0
#  config:
#    import: "optional:configserver:"
springdoc:
  api-docs:
    path: buscacep-service/v3/api-docs
  show-actuator: true

